### PR TITLE
Adding query tooltip

### PR DESCRIPTION
**Pull request by gilbemar**
The text displayed in the tooltip is very easy to change if we want to, this is setting up the functionality.

### CODE REVIEW

**Comment by evankozliner** [comment]
Getting this error: the site works but I can't see the addition (already did the npm install)
screen shot 2017-04-06 at 2 47 00 pm

**Comment by gilbemar** [comment]
try running 
npm install --save v-tooltip

**Comment by evankozliner** [comment]
Right, I'd already tried adding the module. Still running into the issue :/

**Comment by evankozliner** [comment]
Maggie is this working on your computer? I think it would be nice to have but I can't seem to make vue able to see the component

**Comment by gilbemar** [comment]
It is working on my computer, I am looking into it, if we don't have it it's fine, we can just put text on the page

**Pull request closed without merging**
