### PR TITLE
Fundamentals addition

### PR DESCRIPTION
**Pull request by evankozliner**
Creates a new service for fundamentals data

```bash 
cd fundamentals_extractor
python fundamentals_service.py
```

Then make a front end request to `/fundamentals/ticker` (example in the search vue file)

### CODE REVIEW

**Comment by gilbemar** [comment]
Any idea what module ScraXBRL.DataViewer would be in?
Also, the SearchActions.vue breaks the front end but just because it needs spaces in the comments, nothing is really broken

**Comment by thomaj** [comment]
You shouldn't need ScraXBRL.DataViewer, it should be commented out in the file.  I'll look into both those things.

**Comment by thomaj** [comment]
The stuff in my pull request should have that stuff fixed

**Comment by evankozliner** [comment]
For some reason the months are all one off

**Comment by evankozliner** [comment]
To test this use "fundamentals zeus" and looks at "Total Current Liabilities" under https://www.sec.gov/Archives/edgar/data/917470/000143774914007575/zeus20140331_10q.htm

**Comment by evankozliner** [comment]
Actually a month and a year

**Pull request merged**
