### PR TITLE
Responds with question unknown instead of 500s

### PR DESCRIPTION
**Pull request by evankozliner**

### CODE REVIEW

**Comment by evankozliner** [comment]
Anyone who is testing this should try to see if they can get the site to show the *error* page instead of the question unknown page. Also *make sure to check to see if the server has crashed between your tests*. That would be hella embarrassing

**Comment by gilbemar** [comment]
Can we have the server automatically restart if it crashes or is that not possible?

**Comment by gilbemar** [comment]
I was having the server crash due to version date(error at bottom of comment) issues so i added
NaturalLanguageUnderstandingV1.VERSION_DATE_2017_02_27 = '2017-02-27';
 to ~/Fruugal/node_modules/watson-developer-cloud/natural-language-understanding/v1.js
and now the server doesn't crash, with bad questions it just takes me to the /UnknownAnswer page



throw new Error('Argument error: version_date was not specified, use NaturalLanguageUnderstandingV1.VERSION_DATE_2016_01_23');

**Comment by evankozliner** [comment]
Seems to pass the proper tests however everyone will need to run ` 'npm update watson-developer-cloud' `

**Pull request merged**
